import { format } from 'date-fns'
import jsPDF from 'jspdf'
import html2canvas from 'html2canvas'

interface ReportData {
  income: any[]
  expenses: any[]
  budgets: any[]
  savingsGoals: any[]
  recurringTransactions: any[]
  dateRange: {
    start: string
    end: string
  }
}

interface ReportOptions {
  type: 'financial-summary' | 'income-expense' | 'budget-analysis' | 'savings-progress' | 'recurring-transactions'
  format: 'pdf' | 'csv'
  dateRange: 'current-month' | 'last-3-months' | 'last-6-months' | 'last-year' | 'custom'
  customStart?: string
  customEnd?: string
  includeCharts: boolean
  includeDetails: boolean
}

export default class ReportGenerator {
  async generatePDF(data: ReportData, options: ReportOptions): Promise<Blob> {
    const pdf = new jsPDF()
    const pageWidth = pdf.internal.pageSize.getWidth()
    const pageHeight = pdf.internal.pageSize.getHeight()
    let yPosition = 20

    // Helper function to add text with word wrap
    const addText = (text: string, fontSize: number = 12, x: number = 20, y: number = yPosition) => {
      pdf.setFontSize(fontSize)
      const lines = pdf.splitTextToSize(text, pageWidth - x * 2)
      pdf.text(lines, x, y)
      return y + (lines.length * fontSize * 0.35)
    }

    // Add title
    yPosition = addText(`${options.type.replace('-', ' ').toUpperCase()} REPORT`, 18, pageWidth / 2, yPosition, 'center')
    yPosition = addText(`Generated: ${format(new Date(), 'MMM d, yyyy')}`, 10, 20, yPosition)
    yPosition = addText(`Period: ${format(new Date(data.dateRange.start), 'MMM d, yyyy')} - ${format(new Date(data.dateRange.end), 'MMM d, yyyy')}`, 10, 20, yPosition)
    yPosition += 10

    // Generate content based on report type
    switch (options.type) {
      case 'financial-summary':
        yPosition = this.generateFinancialSummary(pdf, data, options, yPosition, addText)
        break
      case 'income-expense':
        yPosition = this.generateIncomeExpenseReport(pdf, data, options, yPosition, addText)
        break
      case 'budget-analysis':
        yPosition = this.generateBudgetAnalysis(pdf, data, options, yPosition, addText)
        break
      case 'savings-progress':
        yPosition = this.generateSavingsProgress(pdf, data, options, yPosition, addText)
        break
      case 'recurring-transactions':
        yPosition = this.generateRecurringTransactions(pdf, data, options, yPosition, addText)
        break
    }

    // Add footer
    const totalPages = pdf.internal.getNumberOfPages()
    for (let i = 1; i <= totalPages; i++) {
      pdf.setPage(i)
      pdf.setFontSize(8)
      pdf.text(`Page ${i} of ${totalPages}`, pageWidth - 30, pageHeight - 10)
      pdf.text('Generated by FinSight AI', 20, pageHeight - 10)
    }

    return new Blob([pdf.output('blob')], { type: 'application/pdf' })
  }

  async generateCSV(data: ReportData, options: ReportOptions): Promise<Blob> {
    let csvContent = ''

    // Add header
    csvContent += `${options.type.replace('-', ' ').toUpperCase()} REPORT\n`
    csvContent += `Generated: ${format(new Date(), 'MMM d, yyyy')}\n`
    csvContent += `Period: ${format(new Date(data.dateRange.start), 'MMM d, yyyy')} - ${format(new Date(data.dateRange.end), 'MMM d, yyyy')}\n\n`

    // Generate content based on report type
    switch (options.type) {
      case 'financial-summary':
        csvContent += this.generateFinancialSummaryCSV(data, options)
        break
      case 'income-expense':
        csvContent += this.generateIncomeExpenseCSV(data, options)
        break
      case 'budget-analysis':
        csvContent += this.generateBudgetAnalysisCSV(data, options)
        break
      case 'savings-progress':
        csvContent += this.generateSavingsProgressCSV(data, options)
        break
      case 'recurring-transactions':
        csvContent += this.generateRecurringTransactionsCSV(data, options)
        break
    }

    return new Blob([csvContent], { type: 'text/csv' })
  }

  private generateFinancialSummary(pdf: jsPDF, data: ReportData, options: ReportOptions, yPosition: number, addText: Function): number {
    // Calculate summary
    const totalIncome = data.income.reduce((sum, item) => sum + item.amount, 0)
    const totalExpenses = data.expenses.reduce((sum, item) => sum + item.amount, 0)
    const netIncome = totalIncome - totalExpenses

    // Summary section
    yPosition = addText('FINANCIAL OVERVIEW', 14, 20, yPosition)
    yPosition = addText(`Total Income: $${totalIncome.toLocaleString()}`, 12, 20, yPosition)
    yPosition = addText(`Total Expenses: $${totalExpenses.toLocaleString()}`, 12, 20, yPosition)
    yPosition = addText(`Net Income: $${netIncome.toLocaleString()}`, 12, 20, yPosition)
    yPosition += 10

    // Income by source
    const incomeBySource = data.income.reduce((acc, item) => {
      acc[item.source] = (acc[item.source] || 0) + item.amount
      return acc
    }, {} as Record<string, number>)

    yPosition = addText('INCOME BY SOURCE', 14, 20, yPosition)
    Object.entries(incomeBySource).forEach(([source, amount]) => {
      yPosition = addText(`${source}: $${amount.toLocaleString()}`, 10, 30, yPosition)
    })
    yPosition += 10

    // Expenses by category
    const expensesByCategory = data.expenses.reduce((acc, item) => {
      acc[item.category] = (acc[item.category] || 0) + item.amount
      return acc
    }, {} as Record<string, number>)

    yPosition = addText('EXPENSES BY CATEGORY', 14, 20, yPosition)
    Object.entries(expensesByCategory).forEach(([category, amount]) => {
      yPosition = addText(`${category}: $${amount.toLocaleString()}`, 10, 30, yPosition)
    })

    return yPosition
  }

  private generateIncomeExpenseReport(pdf: jsPDF, data: ReportData, options: ReportOptions, yPosition: number, addText: Function): number {
    // Income section
    yPosition = addText('INCOME TRANSACTIONS', 14, 20, yPosition)
    yPosition = addText('Date,Source,Amount,Description', 10, 20, yPosition)
    
    data.income.forEach(item => {
      const row = `${format(new Date(item.date), 'MMM d, yyyy')},${item.source},$${item.amount},${item.description || ''}`
      yPosition = addText(row, 9, 20, yPosition)
    })

    yPosition += 10

    // Expenses section
    yPosition = addText('EXPENSE TRANSACTIONS', 14, 20, yPosition)
    yPosition = addText('Date,Category,Amount,Description', 10, 20, yPosition)
    
    data.expenses.forEach(item => {
      const row = `${format(new Date(item.date), 'MMM d, yyyy')},${item.category},$${item.amount},${item.description || ''}`
      yPosition = addText(row, 9, 20, yPosition)
    })

    return yPosition
  }

  private generateBudgetAnalysis(pdf: jsPDF, data: ReportData, options: ReportOptions, yPosition: number, addText: Function): number {
    // Budget performance
    const budgetUtilization = data.budgets.map(budget => {
      const relatedExpenses = data.expenses.filter(expense => expense.category === budget.category)
      const spent = relatedExpenses.reduce((sum, expense) => sum + expense.amount, 0)
      const utilization = (spent / budget.amount) * 100
      return {
        ...budget,
        spent,
        utilization,
        remaining: budget.amount - spent
      }
    })

    yPosition = addText('BUDGET PERFORMANCE', 14, 20, yPosition)
    
    budgetUtilization.forEach(budget => {
      yPosition = addText(`${budget.category}:`, 12, 20, yPosition)
      yPosition = addText(`  Budgeted: $${budget.amount.toLocaleString()}`, 10, 30, yPosition)
      yPosition = addText(`  Spent: $${budget.spent.toLocaleString()}`, 10, 30, yPosition)
      yPosition = addText(`  Remaining: $${budget.remaining.toLocaleString()}`, 10, 30, yPosition)
      yPosition = addText(`  Utilization: ${budget.utilization.toFixed(1)}%`, 10, 30, yPosition)
      yPosition += 5
    })

    return yPosition
  }

  private generateSavingsProgress(pdf: jsPDF, data: ReportData, options: ReportOptions, yPosition: number, addText: Function): number {
    // Savings goals progress
    const savingsProgress = data.savingsGoals.map(goal => ({
      ...goal,
      progress: (goal.current_amount / goal.target_amount) * 100
    }))

    yPosition = addText('SAVINGS GOALS PROGRESS', 14, 20, yPosition)
    
    savingsProgress.forEach(goal => {
      yPosition = addText(`${goal.name}:`, 12, 20, yPosition)
      yPosition = addText(`  Target: $${goal.target_amount.toLocaleString()}`, 10, 30, yPosition)
      yPosition = addText(`  Current: $${goal.current_amount.toLocaleString()}`, 10, 30, yPosition)
      yPosition = addText(`  Remaining: $${(goal.target_amount - goal.current_amount).toLocaleString()}`, 10, 30, yPosition)
      yPosition = addText(`  Progress: ${goal.progress.toFixed(1)}%`, 10, 30, yPosition)
      yPosition += 5
    })

    return yPosition
  }

  private generateRecurringTransactions(pdf: jsPDF, data: ReportData, options: ReportOptions, yPosition: number, addText: Function): number {
    // Recurring transactions overview
    const activeRecurring = data.recurringTransactions.filter(rt => rt.is_active)

    yPosition = addText('RECURRING TRANSACTIONS', 14, 20, yPosition)
    yPosition = addText(`Active Recurring: ${activeRecurring.length}`, 12, 20, yPosition)
    yPosition += 10

    // Income recurring
    const incomeRecurring = activeRecurring.filter(rt => rt.type === 'income')
    yPosition = addText('RECURRING INCOME', 14, 20, yPosition)
    
    incomeRecurring.forEach(rt => {
      yPosition = addText(`${rt.name}: $${rt.amount} (${rt.frequency})`, 10, 20, yPosition)
    })

    yPosition += 10

    // Expense recurring
    const expenseRecurring = activeRecurring.filter(rt => rt.type === 'expense')
    yPosition = addText('RECURRING EXPENSES', 14, 20, yPosition)
    
    expenseRecurring.forEach(rt => {
      yPosition = addText(`${rt.name}: $${rt.amount} (${rt.frequency})`, 10, 20, yPosition)
    })

    return yPosition
  }

  private generateFinancialSummaryCSV(data: ReportData, options: ReportOptions): string {
    const totalIncome = data.income.reduce((sum, item) => sum + item.amount, 0)
    const totalExpenses = data.expenses.reduce((sum, item) => sum + item.amount, 0)
    const netIncome = totalIncome - totalExpenses

    let csv = 'FINANCIAL OVERVIEW\n'
    csv += `Total Income,${totalIncome}\n`
    csv += `Total Expenses,${totalExpenses}\n`
    csv += `Net Income,${netIncome}\n\n`

    // Income by source
    const incomeBySource = data.income.reduce((acc, item) => {
      acc[item.source] = (acc[item.source] || 0) + item.amount
      return acc
    }, {} as Record<string, number>)

    csv += 'INCOME BY SOURCE\n'
    csv += 'Source,Amount\n'
    Object.entries(incomeBySource).forEach(([source, amount]) => {
      csv += `${source},${amount}\n`
    })
    csv += '\n'

    // Expenses by category
    const expensesByCategory = data.expenses.reduce((acc, item) => {
      acc[item.category] = (acc[item.category] || 0) + item.amount
      return acc
    }, {} as Record<string, number>)

    csv += 'EXPENSES BY CATEGORY\n'
    csv += 'Category,Amount\n'
    Object.entries(expensesByCategory).forEach(([category, amount]) => {
      csv += `${category},${amount}\n`
    })

    return csv
  }

  private generateIncomeExpenseCSV(data: ReportData, options: ReportOptions): string {
    let csv = 'INCOME TRANSACTIONS\n'
    csv += 'Date,Source,Amount,Description\n'
    
    data.income.forEach(item => {
      csv += `${format(new Date(item.date), 'MMM d, yyyy')},${item.source},${item.amount},"${item.description || ''}"\n`
    })

    csv += '\nEXPENSE TRANSACTIONS\n'
    csv += 'Date,Category,Amount,Description\n'
    
    data.expenses.forEach(item => {
      csv += `${format(new Date(item.date), 'MMM d, yyyy')},${item.category},${item.amount},"${item.description || ''}"\n`
    })

    return csv
  }

  private generateBudgetAnalysisCSV(data: ReportData, options: ReportOptions): string {
    const budgetUtilization = data.budgets.map(budget => {
      const relatedExpenses = data.expenses.filter(expense => expense.category === budget.category)
      const spent = relatedExpenses.reduce((sum, expense) => sum + expense.amount, 0)
      const utilization = (spent / budget.amount) * 100
      return {
        ...budget,
        spent,
        utilization,
        remaining: budget.amount - spent
      }
    })

    let csv = 'BUDGET PERFORMANCE\n'
    csv += 'Category,Budgeted,Spent,Remaining,Utilization\n'
    
    budgetUtilization.forEach(budget => {
      csv += `${budget.category},${budget.amount},${budget.spent},${budget.remaining},${budget.utilization.toFixed(1)}%\n`
    })

    return csv
  }

  private generateSavingsProgressCSV(data: ReportData, options: ReportOptions): string {
    const savingsProgress = data.savingsGoals.map(goal => ({
      ...goal,
      progress: (goal.current_amount / goal.target_amount) * 100
    }))

    let csv = 'SAVINGS GOALS PROGRESS\n'
    csv += 'Goal,Target,Current,Remaining,Progress\n'
    
    savingsProgress.forEach(goal => {
      csv += `${goal.name},${goal.target_amount},${goal.current_amount},${goal.target_amount - goal.current_amount},${goal.progress.toFixed(1)}%\n`
    })

    return csv
  }

  private generateRecurringTransactionsCSV(data: ReportData, options: ReportOptions): string {
    const activeRecurring = data.recurringTransactions.filter(rt => rt.is_active)

    let csv = 'RECURRING TRANSACTIONS\n'
    csv += 'Name,Type,Amount,Frequency,Next Date,Status\n'
    
    activeRecurring.forEach(rt => {
      csv += `${rt.name},${rt.type},${rt.amount},${rt.frequency},${rt.next_date},${rt.is_active ? 'Active' : 'Paused'}\n`
    })

    return csv
  }
}
